export const allBookings = [
  {
    id: 1,
    firstName: "Anita",
    lastName: "Petrova",
    departureAirport: "SOF",
    destinationAirport: "ROM",
    departureDate: "2025-10-20",
    returnDate: "2025-10-24",
  },
  {
    id: 2,
    firstName: "Maria",
    lastName: "Ivanova",
    departureAirport: "MIL",
    destinationAirport: "SOF",
    departureDate: "2025-10-24",
    returnDate: "2025-10-28",
  },
  {
    id: 3,
    firstName: "Peter",
    lastName: "Jelev",
    departureAirport: "SOF",
    destinationAirport: "VIE",
    departureDate: "2025-10-22",
    returnDate: "2025-10-26",
  },
  {
    id: 4,
    firstName: "Ivan",
    lastName: "Stratiev",
    departureAirport: "FLR",
    destinationAirport: "SOF",
    departureDate: "2025-10-20",
    returnDate: "2025-10-24",
  },
  {
    id: 5,
    firstName: "Silvia",
    lastName: "Nedyalkova",
    departureAirport: "MIL",
    destinationAirport: "SOF",
    departureDate: "2025-10-21",
    returnDate: "2025-10-25",
  },
  {
    id: 6,
    firstName: "Georgi",
    lastName: "Dimitrov",
    departureAirport: "SOF",
    destinationAirport: "BUH",
    departureDate: "2025-11-01",
    returnDate: "2025-11-05",
  },
  {
    id: 7,
    firstName: "Elena",
    lastName: "Popova",
    departureAirport: "VAR",
    destinationAirport: "SOF",
    departureDate: "2025-11-02",
    returnDate: "2025-11-06",
  },
  {
    id: 8,
    firstName: "Dimitar",
    lastName: "Iliev",
    departureAirport: "SOF",
    destinationAirport: "OTP",
    departureDate: "2025-11-03",
    returnDate: "2025-11-07",
  },
  {
    id: 9,
    firstName: "Anna",
    lastName: "Koleva",
    departureAirport: "SOF",
    destinationAirport: "CDG",
    departureDate: "2025-11-04",
    returnDate: "2025-11-08",
  },
  {
    id: 10,
    firstName: "Nikolai",
    lastName: "Petrov",
    departureAirport: "MUC",
    destinationAirport: "SOF",
    departureDate: "2025-11-05",
    returnDate: "2025-11-09",
  },
  {
    id: 11,
    firstName: "Svetla",
    lastName: "Georgieva",
    departureAirport: "SOF",
    destinationAirport: "LIS",
    departureDate: "2025-11-06",
    returnDate: "2025-11-10",
  },
  {
    id: 12,
    firstName: "Boris",
    lastName: "Marinov",
    departureAirport: "PRG",
    destinationAirport: "SOF",
    departureDate: "2025-11-07",
    returnDate: "2025-11-11",
  },
];
